name: Publish to init
on:
  push:
    branches:
      - develop
    paths:
      - "init/**"
permissions:
  statuses: write
  checks: write
jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      SKIP_PREFLIGHT_CHECK: true
      GENERATE_SOURCEMAP: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install -g yarn
      - run: git config --global url."https://".insteadOf git://
      - run: yarn install
      - name: Build
        run: yarn build
      # - name: docker login
      #   env:
      #     DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
      #     DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      #   run: |
      #     docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
     
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build, tag and push image to Amazon ECR
        env:
          DOCKER_REGISTRY: lmartinezs
          DOCKER_REPOSITORY: reactapp
        run: |
          TIMESTAMP=$(date +%s)
          echo "build and push"
          echo $DOCKER_REGISTRY/$DOCKER_REPOSITORY:${GITHUB_SHA::8}-init
          docker build  -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:${GITHUB_SHA::8}-$TIMESTAMP -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:${GITHUB_SHA::8}-init .
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:${GITHUB_SHA::8}-init

