name: Detect Merge Not from PR

on:
  push:
    branches:
      - main  # Cambia 'main' por la rama que te interese

jobs:
  detect-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Check if commit is a merge commit
        id: check_merge_commit
        run: |
          if [ $(git rev-parse --verify -q HEAD^2) ]; then
            echo "is_merge_commit=true" >> $GITHUB_ENV
          else
            echo "is_merge_commit=false" >> $GITHUB_ENV
          fi

      - name: Check if merge commit is not from PR
        id: check_not_pr
        run: |
          if [ "${{ env.is_merge_commit }}" = "true" ]; then
            # Check if there is no PR associated with this commit
            if ! git log -1 --pretty=%B | grep -q "Merge pull request"; then
              echo "is_merge_not_pr=true" >> $GITHUB_ENV
            else
              echo "is_merge_not_pr=false" >> $GITHUB_ENV
            fi
          else
            echo "is_merge_not_pr=false" >> $GITHUB_ENV
          fi

      - name: Output result
        run: |
          if [ "${{ env.is_merge_not_pr }}" = "true" ]; then
            echo "This merge commit is not from a PR."
          else
            echo "This is either not a merge commit or it is a merge from a PR."
          fi
