name: Publish package to GitHub Packages
on:
  # push:
  #   branches:
  #     - develop
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - name: Check package version
        uses: technote-space/package-version-check-action@v1
        with:
          COMMIT_DISABLED: 1
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
          # Defaults to the user or organization that owns the workflow file
          scope: "@lmartinezs"
      - name: Get latest release version
        id: get_version
        run: |
          VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Update package.json version
        run: |
          jq --arg version "$VERSION" '.version = $version' package.json > temp.json
          mv temp.json package.json
        shell: bash
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          yarn install
          yarn publish --non-interactive --new-version $VERSION
